### ISSUE TITLE
Blurred svg while zooming

### ISSUE THREAD

**Issue by robertmanea** [AnkurLahiry/SVGInteraction#2]
Hi,

First of all thanks for the tutorial on this, it helped a lot. However, I cannot figure out why my svgs don't scale when zooming. I've tried this with both your "world" svg and my own svgs. Any guidance here? If it's of any help, I'm running Macaw off of this commit: https://github.com/exyte/Macaw/commit/cfb97d6f7393ebe0e7088c8af3d484ee506de586

Thanks!

**Comment by AnkurLahiry** [comment]
Could you be more specific please?
